name: matrix build
on:
  push:
jobs:
  name: build
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.9', '3.10', '3.11', '3.12']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with: 
          python-version: ${{ matrix.python-version }}
      - name: Show Python version 
        run: python --version
